#include "bf.h"
int main() {
    char mem[256];
    char *ptr = mem;
GT GT GT GT GT GT GT GT GT GT LT LT LT LT LT LT LT LT LT LT PLUS PLUS PLUS PLUS PLUS GT GT GT GT GT GT GT GT GT GT LT LT LT LT LT LT LT LT LT LT OBRA GT PLUS GT PLUS LT LT MINUS CBRA GT GT OBRA LT LT PLUS GT GT MINUS CBRA GT GT GT GT GT GT GT GT LT LT LT LT LT LT LT LT LT LT DOT GT GT GT GT GT GT GT GT GT GT LT LT LT LT LT LT LT LT LT DOT GT GT GT GT GT GT GT GT GT 
printf("result: %d\n", mem[1]);
return 0;}